name: VueJs CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        echo "$(ls -la dist/)" 
        ls 
        
    - uses: actions/checkout@v1
    - run: mkdir -p path/to/artifact
    - run: echo hello > path/to/artifact/world.txt
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: path/to/artifact
      
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: 112.78.2.212
        FTP_USERNAME: admin_aia
        FTP_PASSWORD: Matkhau123!
        LOCAL_DIR: dist
